name: run page://self/
on:
  push:
jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.17.1
        with:
          php-version: "7.4"
      - name: Install dependencies
        run: composer install
  execution:
    runs-on: ubuntu-20.04  
    steps:
      - name: run page://self/
        run: php bin/page.php get '/'
